contracts/authorization/src/contract.rs, contracts/authorization/src/domain.rs, contracts/authorization/src/error.rs, contracts/authorization/src/tests/processor.rs, packages/authorization-utils/src/callback.rs
Closes #19 .
If a user who spent a token to execute a batch (permissioned with limit) couldn't execute anything, his token is given back instead of being consumed.
=> Process tokenfactory tokens during processor callback

local-interchaintest/examples/polytone.rs
Relayer is sometimes too slow due to rate limiting and the packet arrives after the 60 seconds set up as ttl and it makes it not retriable.
Increase TTL time to give more time to the relayer to send the timeout to make sure we don't get false positives for this.
=> Increase TTL time for polytone test

Cargo.lock, Cargo.toml, contracts/authorization/Cargo.toml, contracts/authorization/src/contract.rs, contracts/authorization/src/domain.rs, packages/authorization-utils/Cargo.toml
Move away from NeutronMsg and wasm bindings which ties the authorization contract to Neutron. With this change we can deploy the authorization contract to any tokenfactory chain and move away from what Neutron is deprecating at the moment.
Note: can't use neutron-std or latest commit of neutron-sdk because they inject cosmwasm_2_0 feature and we can't test with it atm. 
Once we can, we can replace neutron-sdk + cosmos-sdk-proto for neutron-std and Stargate for AnyMsg, added TODOs there. Code would be the same.
=> remove NeutronMsg + wasm bindings and use protobuf directly

.github/workflows/check-ci.yml, .gitignore, contracts/authorization/schema/valence-authorization.json, contracts/libraries/astroport-lper/schema/valence-astroport-lper.json, contracts/libraries/astroport-withdrawer/schema/valence-astroport-withdrawer.json, contracts/libraries/forwarder/schema/valence-forwarder-library.json, contracts/libraries/generic-ibc-transfer/schema/valence-generic-ibc-transfer-library.json, contracts/libraries/neutron-ibc-transfer/schema/valence-neutron-ibc-transfer-library.json, contracts/libraries/osmosis-cl-lper/schema/valence-osmosis-cl-lper.json, contracts/libraries/osmosis-cl-withdrawer/schema/valence-osmosis-cl-withdrawer.json, contracts/libraries/osmosis-gamm-lper/schema/valence-osmosis-gamm-lper.json, contracts/libraries/osmosis-gamm-withdrawer/schema/valence-osmosis-gamm-withdrawer.json, contracts/libraries/reverse-splitter/schema/valence-reverse-splitter-library.json, contracts/libraries/splitter/schema/valence-splitter-library.json, contracts/libraries/template/schema/valence-template-library.json, contracts/processor/schema/valence-processor.json, contracts/program-registry/schema/valence-program-registry.json, contracts/testing/test-library/schema/valence-test-library.json, program-manager/schema/valence-program-manager.json
closes #95 
works by generating the schemas in the CI, and asserting that it results in no changes to the file tree.
this way, if any of our contracts api in a given pr had changed, but schemas were not regenerated, the assertion will fail because the up to date schema generated in the job will result in a diff.
=> json schema ci checks

Cargo.lock, Cargo.toml, contracts/accounts/storage_account/.cargo/config.toml, contracts/accounts/storage_account/Cargo.toml, contracts/accounts/storage_account/README.md, contracts/accounts/storage_account/schema/valence-storage-account.json, contracts/accounts/storage_account/src/bin/schema.rs, contracts/accounts/storage_account/src/contract.rs, contracts/accounts/storage_account/src/lib.rs, contracts/accounts/storage_account/src/msg.rs, contracts/accounts/storage_account/src/state.rs, contracts/accounts/storage_account/src/tests.rs, docs/src/components/accounts.md
closes #118 
this is the first version of a storage account meant to:
1. accept arbitrary data being posted
2. make it available via queries
this account will be used for #117  , so changes within this scope are to be expected.
opening this now to avoid a massive pr later down the line.
=> storage account v1

docs/book.toml
making our docs resemble the valence site a little more closely
=> switch to default light theme to match valence site.

solidity/src/processor/LiteProcessor.sol, solidity/src/processor/Processor.sol, solidity/src/processor/ProcessorBase.sol, solidity/src/processor/interfaces/ICallback.sol, solidity/src/processor/interfaces/IProcessor.sol, solidity/src/processor/libs/ProcessorErrors.sol, solidity/src/processor/libs/ProcessorEvents.sol, solidity/test/LiteProcessor.t.sol, solidity/test/Processor.t.sol
Full implementation of EVM LiteProcessor, including atomic/non-atomic execution of batches and callbacks.
This lite version of the processor has no queues nor retries. It receives an encoded message via Hyperlane, decodes it, and executes accordingly depending on the subroutine type.
Since we are going to reuse most of the API for other processor(s) I've separated the code and created multiple libraries/interfaces to make the code more modular/reusable.
NOTE: The subroutine execution/callback will be tested once I have the base account and first service (forwarder) implemented. That is in the next PR. For now I've tested all the functionality that can be tested without these 2.
=> EVM LiteProcessor

docs/book.toml, docs/src/SUMMARY.md, docs/src/examples/_overview.md, docs/src/examples/crosschain_vaults.md
This PR adds specifications to build crosschain vaults using Valence Programs in the Examples section of the docs.
=> Add basic vault docs

contracts/authorization/src/contract.rs, local-interchaintest/examples/polytone.rs
During proxy creation retry, the PendingResponse state was not being saved, which could lead to spam the relayer with useless retry messages.
=> Audit: fix PendingResponse state not being saved during polytone proxy creation retry

contracts/libraries/astroport-lper/src/contract.rs, contracts/libraries/astroport-lper/src/tests.rs, packages/astroport-utils/src/suite.rs
fix the ratio calculation that was being done wrong in the double sided liquidity when we didn't have enough tokens of 1 asset as per audit feedback.
=> Audit: fix astroport ratio calculation

Cargo.lock, contracts/accounts/base_account/schema/valence-base-account.json, contracts/accounts/storage_account/Cargo.toml, contracts/accounts/storage_account/README.md, contracts/accounts/storage_account/schema/valence-storage-account.json, contracts/accounts/storage_account/src/contract.rs, contracts/accounts/storage_account/src/msg.rs, contracts/accounts/storage_account/src/state.rs, contracts/accounts/storage_account/src/tests.rs, contracts/encoders/evm-encoder/schema/valence-evm-encoder-v1.json
work towards #153 
Reworks the storage account contract to store `ValenceType` variants instead of cosmwasm binaries.
Along with that, the api naming is updated:
- for execution, instead of `PostBlob` the storage variant is now called `StoreValenceType`
- for querying, instead of `Blob` the query is now `QueryValenceType`
=> storage account rework

docs/src/authorizations_processors/processor_contract.md
Closes #209 
Add a table in the docs where we describe main differences between processor types, for now Processor and Lite Processor
=> Docs: add table summarizing processor differences

e2e/chains/neutron.json
The neutron RPC running with local-ic will throw CORs errors if you attempt to sign a transaction in the browser with the RPC endpoint. This config will allow all cross origin requests on the RPC API endpoint
=> add local-ic config to prevent CORs errors on neutron node

.github/workflows/check-ci.yml, e2e/examples/persistence_ls.rs, e2e/examples/polytone.rs, e2e/examples/two_party_pol_astroport_neutron.rs, e2e/src/utils/authorization.rs, e2e/src/utils/processor.rs, examples/src/token_swap.rs, justfile
Use osmosis instead of juno for the polytone tests to avoid random panics due to https://github.com/CosmWasm/wasmvm/issues/523 and https://github.com/CosmosContracts/juno/issues/1074 that is making our CI to fail sometimes, more often during rate limiting
=> Change polytone e2e tests to use osmosis instead of juno

examples/src/osmo_cl.rs, examples/src/osmo_gamm.rs
moves the polytone setup  steps in osmosis gamm & cl examples to happen earlier in the run
=> reorg osmo examples polytone setup

e2e/examples/conditional_lp.rs
extending the comments of conditional lp test to highlight the cross-chain error handling and conditional execution capabilities
=> extend `conditional_lp` e2e test description

contracts/libraries/generic-ibc-transfer/README.md, contracts/libraries/generic-ibc-transfer/schema/valence-generic-ibc-transfer-library.json, contracts/libraries/generic-ibc-transfer/src/msg.rs, contracts/libraries/generic-ibc-transfer/src/tests.rs, contracts/libraries/neutron-ibc-transfer/README.md, contracts/libraries/neutron-ibc-transfer/schema/valence-neutron-ibc-transfer-library.json, contracts/libraries/neutron-ibc-transfer/src/tests.rs, docs/src/libraries/cosmwasm/generic_ibc_transfer.md, docs/src/libraries/cosmwasm/neutron_ibc_transfer.md, e2e/examples/conditional_lp.rs, e2e/examples/ibc_transfer_juno_ntrn.rs, e2e/examples/ibc_transfer_ntrn_juno.rs, e2e/examples/ibc_transfer_ntrn_juno_gaia_pfm.rs, e2e/examples/ibc_transfer_osmo_juno_gaia_pfm.rs, e2e/examples/ibc_transfer_osmo_ntrn.rs, program-manager/schema/valence-program-manager.json
We had a small issue in the ibc transfer libraries, where the output (the recipient) address was a string and not `LibraryAccountType`.
The reason we need to work with `LibraryAccountType` even for addresses that are on other chains is that this is our helper type to link an account id to its address.
In short, when you build the program config you use account ids to represent an account, when you use the manager, the manager instantiate the account and "inject" the address where this account id was used.
P.s, an id is only used for valence accounts, if a string is needed when using the `LibraryAccountType` type, you can always use `LibraryAccountType::Addr(String)` to put any string there that represents an address, and in contract use `.to_string()` to get that string.
We probably will …
=> fix ibc transfer

e2e/chains/neutron_noble.json
Adding config here to spin-up noble to set up the chain with all the initial values required to test bridging assets. Doing this PR first in case @bekauz you need to spin up noble for some reason, which I don't think you'll be doing soon but anyways.
Additional things that need to be done to be able to trigger the bridging (reproduced in CLI) and taken from their go integration tests in noble-assets/noble:
```bash
nobled q auth module-accounts
nobled tx fiat-tokenfactory mint noble1hj5fveer5cjtn4wd6wstzugjfdxzl0xpw0865d 1000000uusdc --from admin --chain-id localnoble-1 -y
nobled tx fiat-tokenfactory configure-minter-controller noble1hj5fveer5cjtn4wd6wstzugjfdxzl0xpw0865d noble12l2w4ugfz4m6dd73yysz477jszqnfughxvkss5 --from admin --chain-id localnoble-1 -y
nobled tx fiat-tokenfactory …
```
=> Add noble local-ic config setup

Cargo.lock, contracts/program-registry/schema/valence-program-registry.json, contracts/program-registry/src/contract.rs, contracts/program-registry/src/error.rs, contracts/program-registry/src/state.rs, packages/program-registry-utils/Cargo.toml, packages/program-registry-utils/src/lib.rs, program-manager/src/domain/cosmos_cw.rs
Tested, so it works.
Up until now only the owner of the registry could save programs. 
But this was limiting because it would mean only a single wallet could run the manager (or share access to this wallet to run programs).
Not something we want to do, so we change it to allow anyone use the manager (and save his program to the registry).
Important security here is that we still have program ownership concept here but we have 2 address, the idea is that:
1. The manager reserves and id, so in the meanwhile he is the "temp_owner" of this program id.
2. When the manager saves the program, he also specify which address is the owner, so ownership is transferred to the new owner
3. Only the owner can update that program.
This is done so there won't be any cases where reserved id is saved by …
=> remove admin check from registry

contracts/authorization/schema/valence-authorization.json, contracts/libraries/clearing-queue-supervaults/schema/valence-clearing-queue-supervaults.json, contracts/libraries/clearing-queue-supervaults/src/contract.rs, contracts/libraries/clearing-queue-supervaults/src/msg.rs
- adds `supervaults_phase` bool flag to the library config
- clearing queue obligation registration now branches into different handlers (mars/supervaults) based on the flag which indicates the phase
=> feat: supervaults clearing queue internalize phase flag

contracts/libraries/clearing-queue-supervaults/schema/valence-clearing-queue-supervaults.json, contracts/libraries/clearing-queue-supervaults/src/contract.rs, contracts/libraries/clearing-queue-supervaults/src/msg.rs
Updates the supervaults clearing queue to allow withdrawing from multiple supervaults instead of only one.
Most of the logic change is in the config validation where we validate that we are providing not duplicated supervault addresses and that the ratios are correct and sum up to 100%
=> feat: update supervaults clearing queue to allow multiple supervaults

solidity/src/processor/ProcessorBase.sol
even though this will never happen. we add protection to not allow invalid inputs (these are already checked in current authorization contract but someone may make a different one that doesn't do that check).
We'll return a better error than an out of bounds panic
=> audit: add check for function and message length

solidity/src/vaults/OneWayVault.sol, solidity/test/vaults/OneWayVault.t.sol, solidity/test/vaults/OneWayVaultConfigUpdate.t.sol
separated the config tests into a separate test contract because it was too big to compile (bytecode exceeded maximum)
=> audit: cannot initialize with zero RR

solidity/src/processor/LiteProcessor.sol, solidity/src/processor/Processor.sol, solidity/src/vaults/OneWayVault.sol
even though this won't happen because we authorize addresses to execute on processor. We're protecting from reentrancy tries to reenter the execute function.
Same for the vault. We add reentrancy protection for malicious tokens, even though the vault will only work with trusted tokens.
=> audit: add nonreentrant modifiers

solidity/src/authorization/Authorization.sol, solidity/src/processor/ProcessorBase.sol, solidity/src/vaults/OneWayVault.sol, solidity/src/vaults/ValenceVault.sol
=> audit: misc improvements

solidity/src/vaults/OneWayVault.sol, solidity/src/vaults/ValenceVault.sol
spendAllowance already does the checks inside
```solidity
function _spendAllowance(address owner, address spender, uint256 value) internal virtual {
uint256 currentAllowance = allowance(owner, spender);
if (currentAllowance < type(uint256).max) {
if (currentAllowance < value) {
revert ERC20InsufficientAllowance(spender, currentAllowance, value);
}
unchecked {
_approve(owner, spender, currentAllowance - value, false);
}
}
}
```
=> audit: remove duplicated check

solidity/src/authorization/Authorization.sol, solidity/src/verification/SP1VerificationGateway.sol, solidity/src/verification/VerificationGateway.sol, solidity/test/authorization/AuthorizationZK.t.sol
Use bytes instead of bytes32 in the verification gateway.
What we do then in the SP1 verification gateway when verifying is convert  to bytes32 which is what SP1 in particular will use. This allows having VKs that are not constricted to 32 length for when we support other verifications. 
Similar to what we have in CosmWasm where we are using `Binary` for the VK.
=> feat: use bytes instead of bytes32 in verification gateway

Cargo.lock, contracts/libraries/clearing-queue-supervaults/Cargo.toml, packages/supervaults-utils/Cargo.toml
This PR bumps mmvault package version to the latest version
=> Chore: fix supervaults version in supervaults-utils
